safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
relative_permalinks: false

default_theme: bright
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Gaurav Pareek
    url:  http://grv.rocks/
    company:
        # name: Famous Inc.
        # url:  http://example.com/

fork_url: https://github.com/shower/shower
progress: true
line_numbers: true
